# Generated by Django 4.2.5 on 2023-11-04 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0005_school_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("review_text", models.CharField(max_length=500)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Fall", "Fall"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "grade_received",
                    models.CharField(
                        choices=[
                            ("F", "F"),
                            ("D-", "D-"),
                            ("D", "D"),
                            ("D+", "D+"),
                            ("C-", "C-"),
                            ("C", "C"),
                            ("C+", "C+"),
                            ("B-", "B-"),
                            ("B", "B"),
                            ("B+", "B+"),
                            ("A-", "A-"),
                            ("A", "A"),
                            ("A+", "A+"),
                            ("N/A", "N/A"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("In Person", "In Person"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("helpful_count", models.IntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reviews",
            },
        ),
    ]
