# Generated by Django 4.2.5 on 2023-11-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_course"),
        ("review", "0002_review_recommended_review_textbook_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="school.course",
            ),
        ),
    ]
