# Generated by Django 4.2.5 on 2023-11-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_professor_course_professors"),
        ("review", "0003_review_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="school.professor",
            ),
        ),
    ]
