# Generated by Django 4.2.5 on 2023-11-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_review_professor"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating_clarity_requirements",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_class_time_use",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_course_content",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_course_organization",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_course_overall",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_instructor_contribution",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_instructor_explanation",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_instructor_interest",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_question_quality",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_student_confidence",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating_work_amount",
            field=models.IntegerField(
                choices=[
                    (1, "Very Poor"),
                    (2, "Poor"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
            ),
        ),
    ]
