# Generated by Django 4.2.5 on 2023-10-27 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("long_name", models.CharField(max_length=25, verbose_name="LongName")),
                (
                    "short_name",
                    models.CharField(max_length=5, verbose_name="ShortName"),
                ),
                ("state", models.CharField(max_length=25, verbose_name="State")),
                ("city", models.CharField(max_length=25, verbose_name="City")),
                ("country", models.CharField(max_length=25, verbose_name="Country")),
            ],
            options={
                "verbose_name_plural": "Schools",
            },
        ),
    ]
