# Generated by Django 4.2.5 on 2023-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_school_long_name_alter_school_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="long_name",
            field=models.CharField(
                default="UNLV", max_length=25, unique=True, verbose_name="LongName"
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="short_name",
            field=models.CharField(
                default="UNLV", max_length=5, unique=True, verbose_name="ShortName"
            ),
        ),
    ]
