# Generated by Django 4.2.5 on 2023-10-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_alter_school_long_name_alter_school_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
