# Generated by Django 4.2.5 on 2023-10-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_alter_school_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
