# Generated by Django 4.2.5 on 2023-11-16 01:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=4, verbose_name='SubjectAbbreviation')),
                ('catalog_number', models.CharField(max_length=5, verbose_name='CatalogNumber')),
                ('title', models.CharField(max_length=55, verbose_name='Title')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
