# Generated by Django 4.2.5 on 2023-11-30 04:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "schools",
                    models.ManyToManyField(
                        related_name="professors", to="school.school"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professors",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="professors",
            field=models.ManyToManyField(related_name="courses", to="school.professor"),
        ),
    ]
